version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
  frontend:
    build: ./frontend
    command: bash -c "yarn && yarn start"
    volumes:
      - ./frontend:/code
    ports:
      - "3000:3000"
      - "35729:35729"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  celery:
    build: .
    command: watchmedo auto-restart --directory=/code --recursive -- celery -A avalanche_exercise worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  web:
    build: .
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
      - redis
      - frontend
    stdin_open: true
    tty: true
