# Generated by Django 2.2.7 on 2020-01-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('original_image_key', models.UUIDField()),
                ('black_and_white_image_key', models.UUIDField()),
            ],
        ),
    ]
