# Generated by Django 2.2.7 on 2020-01-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0002_auto_20200102_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='black_and_white_image_key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
